# Site settings
title: Poison Tips
email: recipes@poison.tips
description: > # this means to ignore newlines until "baseurl:"
  Oblique strategies for ruining things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://poison.tips" # the base hostname & protocol for your site
twitter_username: mattkatz
github_username:  mattkatz

# Build settings
markdown: kramdown

# collection

collections:
  recipes:
    output: true
